export const BIKES_TABLE_NAME = "bikes";
export const PIECE_TYPES_TABLE_NAME = "piece_types";
export const PIECE_CATEGORIES_TABLE_NAME = "piece_categories";
export const MAINTENANCE_TYPE_TABLE_NAME = "maintenance_types";
export const CATEGORY_MAINTENANCE_TYPE_TABLE_NAME =
  "category_maintenance_types";
export const PIECES_TABLE_NAME = "pieces";
export const MAINTENANCE_HISTORY_TABLE_NAME = "maintenance_history";

export const CREATE_BIKE_TABLE = `
    CREATE TABLE IF NOT EXISTS ${BIKES_TABLE_NAME} (
      id INTEGER PRIMARY KEY,
      name TEXT NOT NULL,
      brand TEXT,
      model TEXT,
      totalKm INTEGER DEFAULT 0,
      createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
      updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP
    );
`;

export const CREATE_PIECE_TYPE_TABLE = `
  CREATE TABLE IF NOT EXISTS ${PIECE_TYPES_TABLE_NAME} (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    description TEXT
  );
`;

export const CREATE_PIECE_CATEGORY_TABLE = `
  CREATE TABLE IF NOT EXISTS ${PIECE_CATEGORIES_TABLE_NAME} (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    typeId INTEGER NOT NULL,
    name TEXT NOT NULL,
    description TEXT,
    FOREIGN KEY (typeId) REFERENCES ${PIECE_TYPES_TABLE_NAME}(id)
  );
`;

export const CREATE_MAINTENANCE_TYPE_TABLE = `
  CREATE TABLE IF NOT EXISTS ${MAINTENANCE_TYPE_TABLE_NAME} (
    id INTEGER PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT,
    isCritical BOOLEAN
  );`;

export const CREATE_CATEGORY_MAINTENANCE_TYPE_TABLE = `
CREATE TABLE IF NOT EXISTS ${CATEGORY_MAINTENANCE_TYPE_TABLE_NAME} (
  categoryId INTEGER NOT NULL,
  maintenanceTypeId INTEGER NOT NULL,
  recommendedKm INTEGER,
  recommendedDays INTEGER,
  PRIMARY KEY (categoryId, maintenanceTypeId),
  FOREIGN KEY (categoryId) REFERENCES ${PIECE_CATEGORIES_TABLE_NAME}(id),
  FOREIGN KEY (maintenanceTypeId) REFERENCES ${MAINTENANCE_TYPE_TABLE_NAME}(id)
);`;

export const CREATE_PIECE_TABLE = `
CREATE TABLE IF NOT EXISTS ${PIECES_TABLE_NAME} (
  id INTEGER PRIMARY KEY,
  bikeId INTEGER NOT NULL,
  categoryId INTEGER NOT NULL,
  name TEXT NOT NULL,
  description TEXT,
  installDate DATETIME,
  installKm INTEGER,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (bikeId) REFERENCES ${BIKES_TABLE_NAME}(id) ON DELETE CASCADE,
  FOREIGN KEY (categoryId) REFERENCES ${PIECE_CATEGORIES_TABLE_NAME}(id)
);`;

export const CREATE_MAINTENANCE_HISTORY_TABLE = `
CREATE TABLE IF NOT EXISTS ${MAINTENANCE_HISTORY_TABLE_NAME} (
  id INTEGER PRIMARY KEY,
  pieceId INTEGER NOT NULL,
  maintenanceTypeId INTEGER NOT NULL,
  date DATETIME DEFAULT CURRENT_TIMESTAMP,
  kmAtMaintenance INTEGER,
  notes TEXT,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (pieceId) REFERENCES ${PIECES_TABLE_NAME}(id) ON DELETE CASCADE,
  FOREIGN KEY (maintenanceTypeId) REFERENCES ${MAINTENANCE_TYPE_TABLE_NAME}(id)
);`;
